### ISSUE TITLE
Features in PR #8

### ISSUE THREAD

**Issue by spandeyehep** [villano-lab/k100Sim#9]
This PR is targeted towards the simulation of Run-76 of k100 setup at UMN. The aim this run is "N-capture with NaI-array coincidence". 
The changes in the code brings following enhancements:

1. It implements NaI array (20 vertical and 3 horizontal tiles) in the simulation setup which can be activated or deactivated on demand using macro command. Each tile is made "sensitive" with unique detector IDs (1001...1003 for three horizontal tiles and 2001....2020 for twenty vertical tiles). 
2. It can exclusively produce photons isotropically of given energy and at given position by providing custom particle source input file path to the executable as an argument: `./k100sim -c -i <filepath.root> <macro.mac>`. Note that it will override `/gps/*` source provided in the mac file. This feature is especially added to make use of [nrCascadeSim](https://github.com/villano-lab/nrCascadeSim).
3. The output file is now in ROOT tree format as opposed to text file.
4. The CMakeLists.txt file has been updated to accomodate multiple cmake versions.
5. source directory contains `neutron_capture.dat` file which has energy spectrum for thermal neutrons. (Might want to rename file).
6. A dedicated stepping action file has been added that does not do anything but is very useful for debugging and can be updated in future to access simHit information from passive materials.

A quick summary can be found in attached slides.
[k100sim_status_24March2022.pdf](https://github.com/villano-lab/k100Sim/files/8484884/k100sim_status_24March2022.pdf)

**Comment by villaa** [comment]
added by PR #8
